# Generated by Django 5.2.4 on 2025-07-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
